replicaCount: 1
namespace: caliconodedockerstats

imagename: "caliconodedockerstats:latest"

service:
  type: ClusterIP
  port: 9088

CALICONODEDOCKERSTATS_ATTR_NAME: "pull_count"
CALICONODEDOCKERSTATS_TARGET_NAME: "https://hub.docker.com/v2/repositories/calico/node/"
